### ISSUE TITLE
Task list - Add checkmark and animation when user completes a goal

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#21]
Better UI with checkmark

**Comment by rajhraval** [comment]
Would love to work on this.

**Comment by brittanyarima** [comment]
@rajhraval You got it!

**Comment by rajhraval** [comment]
@brittanyarima I added simple animation for checkmark.
Is this desired task outcome?

https://github.com/brittanyarima/Steps/assets/35184001/96d15915-a97f-4d38-aac6-c147d0052ead

**Comment by brittanyarima** [comment]
@rajhraval yes! Perfect! Feel free to submit a PR. 🙌
