### ISSUE TITLE
Ability for users to add their own image as Home Screen background

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#29]

**Comment by josephnoir** [comment]
Hi Brittany, I would like to give this a try.

**Comment by josephnoir** [comment]
I'm new to this. Here is my current idea:

1. Add a new section to `SettingsView` that lets the user select an image.
2. Save the image somehow in `StepsViewModel`. And I'm not sure on this step. If I understand correctly you cannot store an image in `AppStorage`. So far I'm not sure where to put it. I'd appreciate a hint.
3. Make `MountainView` show the user's image, if selected. Or create a new custom view and chose the correct view in `HomeView`. The first one seems easier, but the name doesn't fit anymore if the background image is not a mountain.

Does that sound reasonable?

**Comment by brittanyarima** [comment]
This sounds great!!

I believe you should be able to save to the document directory using
FileManager. Here’s a link that might help!

https://stackoverflow.com/questions/68774346/saving-photos-on-view-in-swiftui

**Comment by josephnoir** [comment]
Addresses in  #65. So this can probably be closed?
