### ISSUE TITLE
Add New tab with week/month step data using SwiftCharts

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#30]
* Create new tab on the TabView

**Comment by WasifRaza123** [comment]
Hey @brittanyarima , I want to work on this.

**Comment by brittanyarima** [comment]
@WasifRaza123, Great! You got it!

**Comment by WasifRaza123** [comment]
Key @brittanyarima , I have some questions regarding the TabView.
1. Will this be a new tab in the tab bar?
2. Are there any reference for the UI design or is it complete based on my personal vision?

**Comment by brittanyarima** [comment]
@WasifRaza123 Yes, this should be a new tab in the tab bar with a reasonable icon and name
I absolutely love what SwiftUI charts is capable of & just think utilizing them could be really cool! 
some examples: https://github.com/jordibruin/Swift-Charts-Examples/tree/main

The app is using mostly native swiftUI design things, so I say stay in that realm but I'm good with whatever UI ideas you have! Just mainly getting at least one chart built using their weekly step data. Even with mock data to start and I can update it with the real HealthKit data.

**Comment by brittanyarima** [comment]
Hope that makes sense! Feel free to ask any questions if not!

**Comment by WasifRaza123** [comment]
Hey @brittanyarima , I have created a basic Week chart.
How to improve this like what else I can add or edit? 

<img width="354" alt="Screenshot 2023-10-03 at 10 10 38 PM" src="https://github.com/brittanyarima/Steps/assets/67188463/1c15ab80-7772-45c1-b3dd-124042f3a5c4">

**Comment by brittanyarima** [comment]
Wow! That looks great!! 
If you wanted to fill up the screen a bit more, you could add a list or something below with some fun facts like "Number of times: Reached goal this week - with the number next to it. & Highest number of steps - with the number. 
Honestly this looks great tho! If you want to stop here, that's fine too & I can make another issue to have someone fill up the screen. If you want to keep working on it, that's great too!

One thing I'd say is maybe to move the Steps tab to the left of Settings? So the Settings Tab is on the far right.

**Comment by WasifRaza123** [comment]
I have completed this @brittanyarima . 
I am also working on some other tasks due to which I was unable to properly design a view for the empty space below the weekly chart.
Pr Link:  https://github.com/brittanyarima/Steps/pull/40

**Comment by brittanyarima** [comment]
@WasifRaza123 this is great! This is so incredibly helpful for getting this tab started. Thanks so much for contributing!
