### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#31]

**Comment by DandyLyons** [comment]
I would like to do this please. 

Also is it okay if I use https://github.com/pointfreeco/swift-custom-dump and/or https://github.com/pointfreeco/swift-snapshot-testing

**Comment by brittanyarima** [comment]
@DandyLyons you got it! Yes, that's totally okay!

**Comment by DandyLyons** [comment]
Is it okay if I start transitioning the codebase over to dependency injection using https://github.com/pointfreeco/swift-dependencies ?

It will make it much easier to test and will minimize accidental side effects (e.g. Network Requests during tests).

**Comment by brittanyarima** [comment]
@DandyLyons go for it!

**Comment by DandyLyons** [comment]
First batch of unit tests are in. I'd like to add more, but many of the Views don't have an extracted ViewModel, which makes it difficult, if not impossible to test. I'd like to extract the ViewModels out of the Views if that is okay. 

For example, I'd like to create an AddTaskViewModel for AddTaskView.

**Comment by brittanyarima** [comment]
@DandyLyons I would love that! That would make things a lot better all around, so I say go for it! I'll create a new issue & assign you to it.
