### ISSUE TITLE
Move all Strings to Constants file

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#37]
There are a lot of long Strings in the app that can be moved to the Constants file to make it a bit more safe.

**Comment by DarkSoul26** [comment]
I just saw the application structure, it supports only MacOs. Sorry but I cannot work on it because of device issues. @brittanyarima can open it for others again.

**Comment by brittanyarima** [comment]
Yes, MacOS is definitely needed! I opened it up again. Thanks for trying though!

**Comment by daljeetseera** [comment]
I will take it @brittanyarima
