### ISSUE TITLE
Rethink Steps Detail View (The view when you click the # of steps on Home Screen)

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#38]
- Take out bar chart (since we are adding a charts tab)
- Animate number of steps circle progress view
- Rethink What this view could show that would be interesting to the user. 
- Is this view needed?

**Comment by WasifRaza123** [comment]
Hi @brittanyarima , In the steps detail view we can add the following details:
* Create a chart for the steps walked wrt to hours of a day. 
* We can add the calories burnt, total time walked, total distance walked as well as percentage of the goal covered (If the ViewModel allows). 

According to me, This view is needed as there is no view that shows the details of the steps walked on that day.
What are your views on this?

**Comment by WasifRaza123** [comment]
But this chart will be related to the number of steps worked in a particular hour on the current day.
And the charts in the new tabView is related to week/month chart. 

If it seems redundant, Then we can only animate number of steps circle progress view and also incorporate total time walked and calories burnt idea.

**Comment by brittanyarima** [comment]
Good point! I say go with your original idea!
I love charts, so I don't mind having a ton in the app 😂

**Comment by WasifRaza123** [comment]
Please assign it to me.

**Comment by brittanyarima** [comment]
@WasifRaza123 you got it!

**Comment by WasifRaza123** [comment]
Hi @brittanyarima ,
I have only added an animation in the circleProgressView But getting unexpected behaviour. I have tried to debug but didn't got any solution yet.
[Video Link](https://github.com/brittanyarima/Steps/assets/67188463/814fc91b-ab57-4b00-86cb-852b68a9df4c)

Code Below:
```
struct CircleProgressBar: View {
    let value: Int
    let maxValue: Int
    @State private var drawingStroke = false
    
    var body: some View {
        ZStack {
            Circle()
                .stroke(.indigo.opacity(0.1), lineWidth: 10)

            Circle()
                .trim(from: 0, to: drawingStroke ? CGFloat(self.value) / CGFloat(self.maxValue) : 0)
                .stroke(.indigo, style: StrokeStyle(lineWidth: 10, lineCap: .round))
                .rotationEffect(.degrees(-90))
                .animation(.easeOut(duration: 3), value: drawingStroke)
                .onAppear {
                    drawingStroke.toggle()
                }
            
            VStack {
                Text("\(value)")
                    .font(.system(size: 40))

                Text("Steps")
                    .foregroundColor(.secondary)
            }
        }
        .frame(width: 200, height: 200)
        .padding()
    }
}
```

**Comment by brittanyarima** [comment]
@WasifRaza123 that is odd! I'll take a more in-depth look on Monday & see if I can see why that's happening!

**Comment by WasifRaza123** [comment]
Hi @brittanyarima , Any updates on this.

**Comment by brittanyarima** [comment]
@WasifRaza123 I haven't been able to figure it out. If you want, you can submit a PR and I'll create a new issue & see if someone is willing to see if they can figure out why it's buggin' out?

**Comment by WasifRaza123** [comment]
Hey @brittanyarima , 
Create Pr [(Link)](https://github.com/brittanyarima/Steps/pull/75)
