### ISSUE TITLE
PRIORITY: Connect Home Screen Widgets to HealthKit

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#47]
Need to make sure we have the right healthKit calls and permissions & connect this to the widget extension
StepsViewModel is where the calls currently are.

**Comment by DandyLyons** [comment]
Have you gotten HealthKit to ask for permission on your device yet? I still don't see it on mine.

**Comment by WasifRaza123** [comment]
@brittanyarima , Does the above issue means that the widget of the steps app should show the app data in it or is it related to something else?
