### ISSUE TITLE
Show Github contributors in Settings Tab 

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#48]
- Create a Navigation Link or button "Contributors" 
- Navigation Link should open to a page/sheet that shows a grid of contributors profile photos

**Comment by Drag0ndust** [comment]
May I work in this issue?

**Comment by brittanyarima** [comment]
@Drag0ndust YES! Thanks!

**Comment by Drag0ndust** [comment]
I added the feature and opened a PR #53

**Comment by brittanyarima** [comment]
@Drag0ndust looks great! THANK YOU!
