### ISSUE TITLE
Bug - Problem with xcconfig files

### ISSUE THREAD

**Issue by Drag0ndust** [brittanyarima/Steps#49]
Currently there are xccofnig files in the root directory and also in the `Steps` directory and their values aren't used correctly.
This seems like a bug which should be fixed, so every developer can use their own bundle identifiers and so on.

Also add the used xcconfig file should be added to the `.gitignore`

**Comment by brittanyarima** [comment]
Oh man! I've got xcconfig files ignored on my end (But I did that 2 days
ago, a bit too late). I look into this again today! Thanks for letting me
know!

**Comment by brittanyarima** [comment]
Working on it!

**Comment by Drag0ndust** [comment]
It is still not working for me :(

**Comment by brittanyarima** [comment]
Are you making sure to name the new config file StepsConfig?
I just tried it & it worked for me!
Let me know if you still have issues!

**Comment by brittanyarima** [comment]
@Drag0ndust I think I see the issue. Trying to fix it now!

**Comment by brittanyarima** [comment]
@Drag0ndust Think I fixed it! Try it when you get a chance & let me know if you still have issues. I didn't factor in the Widget extension and that it needs a different BundleID 🤦‍♀️ Updating the readMe with those instructions now!
