### ISSUE TITLE
Improvement: Automate Unit Tests using GitHub Actions. 

### ISSUE THREAD

**Issue by DandyLyons** [brittanyarima/Steps#59]
Minimize headaches and regressions using automated unit tests on GitHub Actions. We can prevent a PR from merging until it passes all automated tests. 

- GitHub Docs: [Building and testing Swift with GitHub Actions](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift)
- Here's an interesting discussion in another repo working on this same thing: https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/71

**Comment by jyothishjohnson** [comment]
Hi @DandyLyons , as the project currently does not have a testing suite present, we can add a github workflow to only build the project. This will help in automatically stopping the merge for PR for which build is failing.

**Comment by DandyLyons** [comment]
There is a testing suite in a PR, but it's currently tied up in a merge conflict.

**Comment by jyothishjohnson** [comment]
Oh okay. Then once the test suite is merged, we can add a workflow to build and test the project for every PR that points to "_dev_"

**Comment by brittanyarima** [comment]
@jyothishjohnson  @DandyLyons  working on fixing this merge conflict tonight. So everything should be good to keep moving forward by tomorrow!

**Comment by DandyLyons** [comment]
@jyothishjohnson , FYI, the test suite has been merged. 

https://github.com/brittanyarima/Steps/pull/57

**Comment by jyothishjohnson** [comment]
Hi @DandyLyons , Are tests working for you on "dev" branch. I can see this error 


<img width="1447" alt="Screenshot 2023-10-17 at 8 15 00 PM" src="https://github.com/brittanyarima/Steps/assets/29103453/9b9456cd-9533-4b76-b14f-83b95e8a1a5b">


`Cannot find 'AddTaskView' in scope`

**Comment by brittanyarima** [comment]
If you update from the dev branch this should be updated in the newest
version to AddGoalView() instead of AddTaskView().

Hope that helps!

**Comment by jyothishjohnson** [comment]
Hi @brittanyarima , Dev branch still has the code for `AddTaskView `
https://github.com/brittanyarima/Steps/blob/dev/StepsTests/AddTaskViewTests.swift

**Comment by brittanyarima** [comment]
Thanks, I'll check it out!

**Comment by brittanyarima** [comment]
I don’t have time to fix it until this weekend. But if you want to get your
code running. If you go back in the git history you should be able to find
AddGoalView & can manually add it to your branch with any other missing
Goal related files.

What happened was someone changed the Task core data entity to Goal. In my
last merge, it must not have been updated with dev & I must’ve missed it!

**Comment by brittanyarima** [comment]
@jyothishjohnson I fixed it! It was just a name hadn't been changed in the Tests. All working on the dev branch now 👍

**Comment by jyothishjohnson** [comment]
Thanks got it @brittanyarima, I will look into this. You can assign this issue to me.

**Comment by jyothishjohnson** [comment]
Hi @brittanyarima , @DandyLyons  Once this PR is merged to dev branch, it will be protected with GA workflow

**Comment by jyothishjohnson** [comment]
Hi @brittanyarima , i think the current workflow is manually disabled. Could you check this?

![Screenshot 2023-10-22 at 5 59 51 PM](https://github.com/brittanyarima/Steps/assets/29103453/2317defa-ba9f-4367-9316-88d289275bbb)

**Comment by brittanyarima** [comment]
I’ll check it out later today!

**Comment by brittanyarima** [comment]
@jyothishjohnson Ok, I enabled it! 👍

**Comment by jyothishjohnson** [comment]
Hi @brittanyarima , updated Github workflow file to fix testing issues. 

https://github.com/brittanyarima/Steps/pull/87

**Comment by brittanyarima** [comment]
@jyothishjohnson THANK YOU!
