### ISSUE TITLE
Set default steps goal to 10,000 

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#73]
Hi @brittanyarima, 
In stepsViewModel, on [line](https://github.com/brittanyarima/Steps/blob/1c9a0bdff31aa9166a30a29bd62edde2dd402d74/Steps/ViewModel/StepsViewModel.swift#L26) the goal is set to 0 when the user has not set any goal but it should be set to 10000 as the default value. I think that this is a redundant line as the goal value will change when the user changes it as goal is of type @published.

I didn't know of any other way to communicate about the bug so I posted here.

```
self.goal = UserDefaults.standard.integer(forKey: Constants.goalKey)
```

_Originally posted by @WasifRaza123 in https://github.com/brittanyarima/Steps/discussions/72_

**Comment by pansuriyaravi** [comment]
Hey @brittanyarima 

For this can't we use app storage to store it in User Default instead of using it through dependency?  Also rn i have checked the code and it look like we are setting 1000 default steps in init of Steps StepsViewModel. I think it's redundant

```
     @Published var goal: Int = 10_000 {
        didSet {
            self.userDefaults.set(goal, forKey: Constants.goalKey)
        }
    }

    init() {
        self.goal = self.userDefaults.integer(forKey: Constants.goalKey) ?? 10_000

        if HKHealthStore.isHealthDataAvailable() {
            healthStore = HKHealthStore()
        }
        
        self.backgroundImage = loadImage(key: Constants.backgroundImageKey)
    }
```

**Comment by brittanyarima** [comment]
Hey @pansuriyaravi,  I also think app storage would be the best for this too. Would you like to update this in the code? If so, I'll assign you!

**Comment by pansuriyaravi** [comment]
Yes, i would love to do that

**Comment by brittanyarima** [comment]
@pansuriyaravi great! I assigned you! 😁
