### ISSUE TITLE
Add User Profile Section

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#76]
- User can select their profile image and set their name

**Comment by Yashraj49** [comment]
hello @brittanyarima assign me this issue.

**Comment by Yashraj49** [comment]
hey @brittanyarima should I also add contact us after privacy policy , so when user clicks on it it gets redirected to the default e-mail app with the developer 's email id as recipient to contact the developer . 
also can you add Hacktoberfest fest tag to this issue .
